title: David Letscher
email: david.letscher@slu.edu
description: >-
  Thoughts on CS pedagogy and AI use in CS education.
baseurl: ""
url: "https://davidletscher.github.io"
author: David Letscher
github_username: davidletscher

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/
markdown: kramdown
timezone: America/Chicago

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude:
  - vendor/
  - README.md
